version: 2

sources:
  - name: olist_raw
    schema: olist_raw
    tables:
      - name: orders
      - name: customer
      - name: order_items
      - name: products
      - name: sellers
      - name: order_payments
      - name: order_reviews
      - name: geolocation
