config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    bigquery:
      type: bigquery
      threads: 2
      method: service-account
      project: "{{ env_var('TARGET_BIGQUERY_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_TARGET_SCHEMA') }}"
      keyfile: "{{ env_var('TARGET_BIGQUERY_CREDENTIALS_PATH') }}"
      location: "{{ env_var('TARGET_BIGQUERY_LOCATION') }}"
